name: pf_balancing_gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.4.0
  - blas=1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.10.8
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cryptography=3.4.8
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - cycler=0.11.0
  - dataclasses=0.8
  - fonttools=4.29.1
  - freetype=2.10.4
  - frozenlist=1.2.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - h5py=3.6.0
  - hdf5=1.10.6
  - icc_rt=2019.0.0
  - icu=68.1
  - idna=3.3
  - importlib-metadata=4.8.2
  - intel-openmp=2021.4.0
  - jpeg=9d
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=11.1.0
  - libcurl=7.80.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libssh2=1.9.0
  - libtiff=4.0.10
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.1.0
  - munkres=1.1.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - oauthlib=3.1.1
  - olefile=0.46
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - packaging=21.3
  - pillow=8.4.0
  - pip=21.2.4
  - protobuf=3.14.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - qt=5.12.9
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.7.3
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.37.2
  - tensorboard=2.5.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.5.0
  - tensorflow-base=2.5.0
  - tensorflow-estimator=2.5.0
  - tensorflow-gpu=2.5.0
  - termcolor=1.1.0
  - tk=8.6.11
  - tornado=6.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.0.2
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.13.3
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - colorama==0.4.4
    - flatbuffers==1.12
    - grpcio==1.34.1
    - joblib==1.1.0
    - keras==2.8.0
    - lxml==4.7.1
    - networkx==2.6.3
    - pandas==1.4.0
    - pytz==2021.3
    - scikit-learn==1.0.2
    - spektral==1.0.6
    - tensorboard-data-server==0.6.1
    - threadpoolctl==3.1.0
    - tqdm==4.62.3
