name: pf_balancing_gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cudatoolkit=11.3.1
  - cudnn=8.2.1.32
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=21.2.4
  - python=3.9.7
  - python_abi=3.9
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==0.15.0
    - astunparse==1.6.3
    - cachetools==5.2.0
    - charset-normalizer==2.0.12
    - cycler==0.11.0
    - flatbuffers==1.12
    - fonttools==4.33.3
    - gast==0.4.0
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==3.3
    - importlib-metadata==4.11.4
    - joblib==1.1.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - lxml==4.9.0
    - markdown==3.3.7
    - matplotlib==3.5.1
    - networkx==2.8.3
    - numpy==1.19.5
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.2
    - pillow==9.1.1
    - protobuf==3.20.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - six==1.15.0
    - spektral==1.0.6
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tqdm==4.64.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - wrapt==1.12.1
    - zipp==3.8.0