name: pf_balancing_gnn
channels:
  - conda-forge
dependencies:
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.1.3
  - cryptography=37.0.2
  - cycler=0.11.0
  - fonttools=4.33.3
  - freetype=2.10.4
  - frozenlist=1.3.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.6.6
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.39.1
  - grpcio=1.39.0
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.11.4
  - jpeg=9e
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libcxx=14.0.4
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markdown=3.3.7
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.19.5
  - oauthlib=3.2.0
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - opt_einsum=3.3.0
  - packaging=21.3
  - pillow=9.1.1
  - pip=22.1.2
  - protobuf=3.16.0
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pyu2f=0.1.5
  - re2=2021.09.01
  - readline=8.1
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scipy=1.8.1
  - setuptools=62.3.2
  - six=1.15.0
  - snappy=1.1.9
  - sqlite=3.38.5
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - tk=8.6.12
  - tornado=6.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - werkzeug=2.1.2
  - wheel=0.37.1
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - joblib==1.1.0
    - lxml==4.9.0
    - networkx==2.8.3
    - pandas==1.4.2
    - pytz==2022.1
    - scikit-learn==1.1.1
    - spektral==1.0.6
    - threadpoolctl==3.1.0
    - tqdm==4.64.0
